### ISSUE TITLE
Hipster Webpart issue in SharePoint Online

### ISSUE THREAD

**Issue by SharePointAdmin1** [mrackley/ModernHillbillyTabs#2]
Hello, 
The Hipster Webpart is having some sort of issue when loading a page in SharePoint -Online. When loading the page all contents in the tabs appear all at once not under tabs but then quickly disappear then when using tabs the content is not in the tabs? Once a refresh is done to the page all the content is there in the tabs as expected but this could cause some confusion for our users when going to the page at first and not seeing any content available within the tabs at first. 

Can you please fix this or look into?

Thank you.

**Comment by StfBauer** [comment]
This Hipster web part highly experimental and just a demo not meant to used anywhere.

**Comment by SharePointAdmin1** [comment]
That's really to bad not supporting your own code : ( ? It was really nice looking on SharePoint pages and organized things nicely. Guess we will have to remove all these from our company pages very sad.

**Comment by StfBauer** [comment]
It was just a prototype and honestly, I don't really have time. What you can do is download the code and try to fix it yourself.
